from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, Field


class TechRadarAnalysis(BaseModel):
    """
    Structured analysis schema returned by the LLM for the Tech Radar dashboard.
    All content values are in Vietnamese.
    """
    category: str = Field(
        ...,
        description="One of 7 predefined Tech Radar categories in Vietnamese."
    )
    relevance_score: int = Field(
        ...,
        ge=1, le=10,
        description="Impact score for an AI software engineer (1-10)."
    )
    tl_dr: str = Field(
        ...,
        description="1-2 sentence summary of the core event/news in Vietnamese."
    )
    key_insights: List[str] = Field(
        ...,
        description="3-4 technical insights: the 'what', 'how', and 'why'."
    )
    tech_stack: List[str] = Field(
        default_factory=list,
        description="Models, frameworks, or libraries mentioned."
    )
    why_it_matters: str = Field(
        ...,
        description="One sentence on the practical value or impact on developers."
    )


class Article(BaseModel):
    """
    Data Contract for an Article across all modules in the Hermes AI News Agent.
    The 'analysis' field replaces the old plain-text 'summary' field.
    """
    source_url: str = Field(..., description="The URL of the original article")
    title: str = Field(..., description="The title of the article")
    raw_text: str = Field(..., description="The full, unparsed text of the article")
    published_at: datetime = Field(..., description="The publication timestamp")
    analysis: Optional[TechRadarAnalysis] = Field(
        default=None,
        description="Structured Tech Radar analysis generated by the LLM"
    )
    # Keep summary as a plain-text fallback field (e.g., for backward compatibility)
    summary: Optional[str] = Field(
        default=None,
        description="[Deprecated] Legacy plain-text summary field"
    )
    tags: List[str] = Field(default_factory=list, description="Categorization tags")
